name: Deploy

on:
    push:
        branches: [ master ]

jobs:
    deploy-sonatype:
        name: Deploy to sonatype
        runs-on: ubuntu-latest
        timeout-minutes: 10
        environment: ossrh
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
            - name: Build and publish
              env:
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
                  MAVEN_SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
                  MAVEN_SIGNING_PASSWORD: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
              run: ./gradlew publishToSonatype closeSonatypeStagingRepository --stacktrace
